#cloud-config
timezone: Europe/Kiev
users:
  - name: bikoadmin
    uid: 1000
    gid: 1000
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD2W9EXH66GBjLHDyv9ztWn3J1YcOoqlGqZDHAbeEYlxLz2ju06dPrSTjxiuabeDhF3Nu7BDykhOBikn+Hsj4KTzEEEX8mqC+94Z39DgFn2trgEV205vgl7FnBEVKQAMFvXsW7NH5Tl8eyIvyALNFbwPT5FtV9CVgkmLIWuJHDQQiztDRFihbXU2JXKvd4PnLAwoBvohtPJ/HO9b6tO18OAGopAHWmhDwAYaz1CsDE8k8A1hCOOrvah9CBjdU5wicmcVGacCcUNav1ij6Km/k9XJfji5Png88tSWx0PYE1Hu4i+jWT8yLbDDEJDRqXP2fLMvDc2jXsQ1rZuZpkAC+VMU9/zWsZMKv3lpTfN2S3TG/wXalyJx9AxqrTDBG/myFiGzA9Z7uOA2P/lHh/VmIh5dDX+ZjF7djH7o5z73eKVHuc/ryyU/2FEc5pWiSRJHAQ4vVx+EuVYmRXtL7K4ZjYSOia+RokevhBgxrlxuLyF+sMsz1r9zeZybGKS/ju4/p0= external sysadmin
package_update: true
package_upgrade: true
packages:
  - ufw
  - mc
  - software-properties-common
runcmd:
  #configuring fail2ban
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  #UFW config
  - ufw allow OpenSSH
  - ufw allow from any to any port 80
  - ufw allow from any to any port 443
  - ufw enable
  #configuring SSH
  - sed -i 's/[#]*PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers bikoadmin' /etc/ssh/sshd_config
  - reboot
